var data = [{
    "id": 1,
    "x": 0,
    "y": 0,
    "row": 1,
    "selected": "noSelected"
},{
    "id": 2,
    "x": 50,
    "y": 0,
    "row": 1,
    "selected": "noSelected"
}, {
    "id": 3,
    "x": 150,
    "y": 0,
    "row": 1,
    "selected": "noSelected"
}, {
    "id": 4,
    "x": 200,
    "y": 0,
    "row": 1,
    "selected": "noSelected"
}, {
    "id": 5,
    "x": 250,
    "y": 0,
    "row": 1,
    "selected": "chosen"
}, {
    "id": 6,
    "x": 300,
    "y": 0,
    "row": 1,
    "selected": "chosen" 
}, {
    "id": 7,
    "x": 350,
    "y": 0,
    "row": 1,
    "selected": "chosen" 
}, {
    "id": 8,
    "x": 400,
    "y": 0,
    "row": 1,
    "selected": "chosen" 
}, {
    "id": 9,
    "x": 450,
    "y": 0,
    "row": 1,
    "selected": "chosen" 
}, {
    "id": 10,
    "x": 500,
    "y": 0,
    "row": 1,
    "selected": "chosen" 
}, {
    "id": 11,
    "x": 550,
    "y": 0,
    "row": 1,
    "selected": "chosen" 
}, {
    "id": 12,
    "x": 600,
    "y": 0,
    "row": 1,
    "selected": "chosen" 
}, {
    "id": 13,
    "x": 650,
    "y": 0,
    "row": 1,
    "selected": "chosen" 
}, {
    "id": 15,
    "x": 700,
    "y": 0,
    "row": 1,
    "selected": "chosen" 
}, {
    "id": 16,
    "x": 0,
    "y": 50,
    "row": 1,
    "selected": "chosen" 
}, {
    "id": 17,
    "x": 50,
    "y": 50,
    "row": 1,
    "selected": "noSelected"
}, {
    "id": 18,
    "x": 150,
    "y": 50,
    "row": 1,
    "selected": "noSelected"//////////////////////////////////
}, {
    "id": 19,
    "x": 200,
    "y": 50,
    "row": 2,
    "selected": "noSelected"
}, {
    "id": 20,
    "x": 250,
    "y": 50,
    "row": 2,
    "selected": "noSelected"
}, {
    "id": 21,
    "x": 300,
    "y": 50,
    "row": 2,
    "selected": "noSelected"
}, {
    "id": 22,
    "x": 350,
    "y": 50,
    "row": 2,
    "selected": "noSelected"
}, {
    "id": 23,
    "x": 400,
    "y": 50,
    "row": 2,
    "selected": "noSelected"
}, {
    "id": 24,
    "x": 450,
    "y": 50,
    "row": 2,
    "selected": "noSelected"
}, {
    "id": 25,
    "x": 500,
    "y": 50,
    "row": 2,
    "selected": "noSelected"
}, {
    "id": 26,
    "x": 550,
    "y": 50,
    "row": 2,
    "selected": "noSelected"
}, {
    "id": 27,
    "x": 600,
    "y": 50,
    "row": 2,
    "selected": "noSelected"
}, {
    "id": 28,
    "x": 650,
    "y": 50,
    "row": 2,
    "selected": "noSelected"
}, {
    "id": 29,
    "x": 700,
    "y": 50,
    "row": 2,
    "selected": "noSelected"////////////////////////////////////////////
}, {
    "id": 30,
    "x": 0,
    "y": 100,
    "row": 3,
    "selected": "noSelected"
},{
    "id": 31,
    "x": 50,
    "y": 100,
    "row": 3,
    "selected": "noSelected"
}, {
    "id": 32,
    "x": 150,
    "y": 100,
    "row": 3,
    "selected": "noSelected"
}, {
    "id": 33,
    "x": 200,
    "y": 100,
    "row": 3,
    "selected": "noSelected"
}, {
    "id": 34,
    "x": 250,
    "y": 100,
    "row": 3,
    "selected": "noSelected"
}, {
    "id": 35,
    "x": 300,
    "y": 100,
    "row": 3,
    "selected": "noSelected"
}, {
    "id": 36,
    "x": 350,
    "y": 100,
    "row": 3,
    "selected": "noSelected"
}, {
    "id": 37,
    "x": 400,
    "y": 100,
    "row": 3,
    "selected": "noSelected"
}, {
    "id": 38,
    "x": 450,
    "y": 100,
    "row": 3,
    "selected": "noSelected"
}, {
    "id": 39,
    "x": 500,
    "y": 100,
    "row": 3,
    "selected": "noSelected"
}, {
    "id": 40,
    "x": 550,
    "y": 100,
    "row": 3,
    "selected": "noSelected"
}, {
    "id": 41,
    "x": 600,
    "y": 100,
    "row": 3,
    "selected": "noSelected"
}, {
    "id": 42,
    "x": 650,
    "y": 100,
    "row": 3,
    "selected": "noSelected"
}, {
    "id": 43,
    "x": 700,
    "y": 100,
    "row": 3,
    "selected": "noSelected"
},  {
    "id": 44,
    "x": 800,
    "y": 100,
    "row": 3,
    "selected": "noSelected"
}, {
    "id": 45,
    "x": 850,
    "y": 100,
    "row": 3,
    "selected": "noSelected" //////////////////////////////////////////
}, { 
    "id": 46,
    "x": 0,
    "y": 150,
    "row": 4,
    "selected": "noSelected" 
}, {
    "id": 47,
    "x": 50,
    "y": 150,
    "row": 4,
    "selected": "noSelected"
}, {
    "id": 48,
    "x": 150,
    "y": 150,
    "row": 4,
    "selected": "noSelected"
}, {
    "id": 49,
    "x": 200,
    "y": 150,
    "row": 4,
    "selected": "noSelected"
}, {
    "id": 50,
    "x": 250,
    "y": 150,
    "row": 4,
    "selected": "noSelected"
}, {
    "id": 51,
    "x": 300,
    "y": 150,
    "row": 4,
    "selected": "noSelected"
}, {
    "id": 52,
    "x": 350,
    "y": 150,
    "row": 4,
    "selected": "noSelected"
}, {
    "id": 53,
    "x": 400,
    "y": 150,
    "row": 4,
    "selected": "noSelected"
}, {
    "id": 54,
    "x": 450,
    "y": 150,
    "row": 4,
    "selected": "noSelected"
}, {
    "id": 55,
    "x": 500,
    "y": 150,
    "row": 4,
    "selected": "noSelected"
}, {
    "id": 56,
    "x": 550,
    "y": 150,
    "row": 4,
    "selected": "noSelected"
}, {
    "id": 57,
    "x": 600,
    "y": 150,
    "row": 4,
    "selected": "noSelected"
}, {
    "id": 58,
    "x": 650,
    "y": 150,
    "row": 4,
    "selected": "noSelected"
}, {
    "id": 59,
    "x": 700,
    "y": 150,
    "row": 4,
    "selected": "noSelected" 
}, {
    "id": 60,
    "x": 800,
    "y": 150,
    "row": 4,
    "selected": "noSelected"
}, {
    "id": 61,
    "x": 850,
    "y": 150,
    "row": 4,
    "selected": "noSelected" ////////////////////////////////
}, {
    "id": 62,
    "x": 0,
    "y": 200,
    "row": 5,
    "selected": "noSelected"
}, {
    "id": 63,
    "x": 50,
    "y": 200,
    "row": 5,
    "selected": "noSelected"
}, {
    "id": 64,
    "x": 150,
    "y": 200,
    "row": 5,
    "selected": "noSelected"
}, {
    "id": 65,
    "x": 200,
    "y": 200,
    "row": 5,
    "selected": "noSelected"
}, {
    "id": 66,
    "x": 250,
    "y": 200,
    "row": 5,
    "selected": "noSelected"
}, {
    "id": 67,
    "x": 300,
    "y": 200,
    "row": 5,
    "selected": "noSelected"
}, {
    "id": 68,
    "x": 350,
    "y": 200,
    "row": 5,
    "selected": "noSelected"
}, {
    "id": 69,
    "x": 400,
    "y": 200,
    "row": 5,
    "selected": "noSelected"
}, {
    "id": 70,
    "x": 450,
    "y": 200,
    "row": 5,
    "selected": "noSelected"
}, {
    "id": 71,
    "x": 500,
    "y": 200,
    "row": 5,
    "selected": "noSelected"
}, {
    "id": 72,
    "x": 550,
    "y": 200,
    "row": 5,
    "selected": "noSelected"
}, {
    "id": 73,
    "x": 600,
    "y": 200,
    "row": 5,
    "selected": "noSelected"
}, {
    "id": 74,
    "x": 650,
    "y": 200,
    "row": 5,
    "selected": "noSelected"
}, {
    "id": 75,
    "x": 700,
    "y": 200,
    "row": 5,
    "selected": "noSelected" 
}, {
    "id": 76,
    "x": 800,
    "y": 200,
    "row": 5,
    "selected": "noSelected"
}, {
    "id": 77,
    "x": 850,
    "y": 200,
    "row": 5,
    "selected": "noSelected" ////////////////////////////////
},{
    "id": 78,
    "x": 0,
    "y": 250,
    "row": 6,
    "selected": "noSelected"
}, {
    "id": 79,
    "x": 50,
    "y": 250,
    "row": 6,
    "selected": "noSelected"
}, {
    "id": 80,
    "x": 150,
    "y": 250,
    "row": 6,
    "selected": "noSelected"
}, {
    "id": 81,
    "x": 200,
    "y": 250,
    "row": 6,
    "selected": "noSelected"
}, {
    "id": 82,
    "x": 250,
    "y": 250,
    "row": 6,
    "selected": "noSelected"
}, {
    "id": 83,
    "x": 300,
    "y": 250,
    "row": 6,
    "selected": "noSelected"
}, {
    "id": 84,
    "x": 350,
    "y": 250,
    "row": 6,
    "selected": "noSelected"
}, {
    "id": 85,
    "x": 400,
    "y": 250,
    "row": 6,
    "selected": "noSelected"
}, {
    "id": 86,
    "x": 450,
    "y": 250,
    "row": 6,
    "selected": "noSelected"
}, {
    "id": 87,
    "x": 500,
    "y": 250,
    "row": 6,
    "selected": "noSelected"
}, {
    "id": 88,
    "x": 550,
    "y": 250,
    "row": 6,
    "selected": "noSelected"
}, {
    "id": 89,
    "x": 600,
    "y": 250,
    "row": 6,
    "selected": "noSelected"
}, {
    "id": 90,
    "x": 650,
    "y": 250,
    "row": 6,
    "selected": "noSelected"
}, {
    "id": 91,
    "x": 700,
    "y": 250,
    "row": 6,
    "selected": "noSelected" 
}, {
    "id": 92,
    "x": 800,
    "y": 250,
    "row": 6,
    "selected": "noSelected"
}, {
    "id": 93,
    "x": 850,
    "y": 250,
    "row": 6,
    "selected": "noSelected" ////////////////////////////////
}, {
    "id": 94,
    "x": 0,
    "y": 300,
    "row": 7,
    "selected": "noSelected"
}, {
    "id": 95,
    "x": 50,
    "y": 300,
    "row": 7,
    "selected": "noSelected"
}, {
    "id": 96,
    "x": 150,
    "y": 300,
    "row": 7,
    "selected": "noSelected"
}, {
    "id": 97,
    "x": 200,
    "y": 300,
    "row": 7,
    "selected": "noSelected"
}, {
    "id": 98,
    "x": 250,
    "y": 300,
    "row": 7,
    "selected": "noSelected"
}, {
    "id": 99,
    "x": 300,
    "y": 300,
    "row": 7,
    "selected": "noSelected"
}, {
    "id": 100,
    "x": 350,
    "y": 300,
    "row": 7,
    "selected": "noSelected"
}, {
    "id": 101,
    "x": 400,
    "y": 300,
    "row": 7,
    "selected": "noSelected"
}, {
    "id": 102,
    "x": 450,
    "y": 300,
    "row": 7,
    "selected": "noSelected"
}, {
    "id": 103,
    "x": 500,
    "y": 300,
    "row": 7,
    "selected": "noSelected"
}, {
    "id": 104,
    "x": 550,
    "y": 300,
    "row": 7,
    "selected": "noSelected"
}, {
    "id": 105,
    "x": 600,
    "y": 300,
    "row": 7,
    "selected": "noSelected"
}, {
    "id": 106,
    "x": 650,
    "y": 300,
    "row": 7,
    "selected": "noSelected"
}, {
    "id": 107,
    "x": 700,
    "y": 300,
    "row": 7,
    "selected": "noSelected" 
}, {
    "id": 108,
    "x": 800,
    "y": 300,
    "row": 7,
    "selected": "noSelected"
}, {
    "id": 109,
    "x": 850,
    "y": 300,
    "row": 7,
    "selected": "noSelected" ////////////////////////////////
}, {
    "id": 110,
    "x": 0,
    "y": 350,
    "row": 8,
    "selected": "noSelected"
}, {
    "id": 111,
    "x": 50,
    "y": 350,
    "row": 8,
    "selected": "noSelected"
}, {
    "id": 112,
    "x": 150,
    "y": 350,
    "row": 8,
    "selected": "noSelected"
}, {
    "id": 113,
    "x": 200,
    "y": 350,
    "row": 8,
    "selected": "noSelected"
}, {
    "id": 114,
    "x": 250,
    "y": 350,
    "row": 8,
    "selected": "noSelected"
}, {
    "id": 115,
    "x": 300,
    "y": 350,
    "row": 8,
    "selected": "noSelected"
}, {
    "id": 116,
    "x": 350,
    "y": 350,
    "row": 8,
    "selected": "noSelected"
}, {
    "id": 117,
    "x": 400,
    "y": 350,
    "row": 8,
    "selected": "noSelected"
}, {
    "id": 118,
    "x": 450,
    "y": 350,
    "row": 8,
    "selected": "noSelected"
}, {
    "id": 119,
    "x": 500,
    "y": 350,
    "row": 8,
    "selected": "noSelected"
}, {
    "id": 120,
    "x": 550,
    "y": 350,
    "row": 8,
    "selected": "noSelected"
}, {
    "id": 121,
    "x": 600,
    "y": 350,
    "row": 8,
    "selected": "noSelected"
}, {
    "id": 122,
    "x": 650,
    "y": 350,
    "row": 8,
    "selected": "noSelected"
}, {
    "id": 123,
    "x": 700,
    "y": 350,
    "row": 8,
    "selected": "noSelected" 
}, {
    "id": 124,
    "x": 800,
    "y": 350,
    "row": 8,
    "selected": "noSelected"
}, {
    "id": 125,
    "x": 850,
    "y": 350,
    "row": 8,
    "selected": "noSelected" ////////////////////////////////
}, {
    "id": 126,
    "x": 0,
    "y": 400,
    "row": 9,
    "selected": "noSelected"
}, {
    "id": 127,
    "x": 50,
    "y": 400,
    "row": 9,
    "selected": "noSelected"
}, {
    "id": 128,
    "x": 150,
    "y": 400,
    "row": 9,
    "selected": "noSelected"
}, {
    "id": 129,
    "x": 200,
    "y": 400,
    "row": 9,
    "selected": "noSelected"
}, {
    "id": 130,
    "x": 250,
    "y": 400,
    "row": 9,
    "selected": "noSelected"
}, {
    "id": 131,
    "x": 300,
    "y": 400,
    "row": 9,
    "selected": "noSelected"
}, {
    "id": 132,
    "x": 350,
    "y": 400,
    "row": 9,
    "selected": "noSelected"
}, {
    "id": 133,
    "x": 400,
    "y": 400,
    "row": 9,
    "selected": "noSelected"
}, {
    "id": 134,
    "x": 450,
    "y": 400,
    "row": 9,
    "selected": "noSelected"
}, {
    "id": 135,
    "x": 500,
    "y": 400,
    "row": 9,
    "selected": "noSelected"
}, {
    "id": 136,
    "x": 550,
    "y": 400,
    "row": 9,
    "selected": "noSelected"
}, {
    "id": 137,
    "x": 600,
    "y": 400,
    "row": 9,
    "selected": "noSelected"
}, {
    "id": 138,
    "x": 650,
    "y": 400,
    "row": 9,
    "selected": "noSelected"
}, {
    "id": 139,
    "x": 700,
    "y": 400,
    "row": 9,
    "selected": "noSelected" 
}, , {
    "id": 140,
    "x": 800,
    "y": 400,
    "row": 9,
    "selected": "noSelected"
}, {
    "id": 141,
    "x": 850,
    "y": 400,
    "row": 9,
    "selected": "noSelected" ////////////////////////////////
}];